### ISSUE TITLE
About Inference Speed

### ISSUE THREAD

**Issue by RohollahHS** [exitudio/BAMM#7]
Hi Ekkasit,

Thanks for the great work and for releasing the code. Did you conduct experiments to compare the inference speed of BAMM with other models, such as MMM and Momask?

Thanks

**Comment by exitudio** [comment]
Hi Sayed,
  Speed is not an advantage for BAMM. I tested on NVIDIA RTX A5000. The average time is around  0.411 s. It's the same server that is used in Table 7 of MMM. MMM is around 0.081 s. MoMask should be around 0.1xx s.

**Comment by RohollahHS** [comment]
Thanks for your reply.
